spring:
  application:
    name: masterFix

  datasource:
    url: jdbc:postgresql://localhost:5434/ustafix_db
    username: postgres
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration: ${JWT_EXPIRATION_MS:900000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION_MS:604800000}